synectura-web:
    container_name: paydibujos_frontend
    # CAMBIO: Ahora apunta a la carpeta frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # ... el resto sigue igual