services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=paydibujos_db'
      - 'POSTGRES_PASSWORD=synectura_user'
      - 'POSTGRES_USER=secretpassword'
    ports:
      - '5432'
